// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxK_aD3UbWLB56wAosytSSUOGcEHUzDpA',
    appId: '1:807190543184:web:f7b37c353abf682d54ca55',
    messagingSenderId: '807190543184',
    projectId: 'pet-pal-e8664',
    authDomain: 'pet-pal-e8664.firebaseapp.com',
    storageBucket: 'pet-pal-e8664.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyIIcsb9ijEWCM0CrygED8Ckbie6UVryI',
    appId: '1:807190543184:android:754601ac6f8d396654ca55',
    messagingSenderId: '807190543184',
    projectId: 'pet-pal-e8664',
    storageBucket: 'pet-pal-e8664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKM0VoQUO8nmMY1SLDWl6dqrZa9k5_4nA',
    appId: '1:807190543184:ios:899e98a5341aa43d54ca55',
    messagingSenderId: '807190543184',
    projectId: 'pet-pal-e8664',
    storageBucket: 'pet-pal-e8664.appspot.com',
    iosBundleId: 'com.example.petpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKM0VoQUO8nmMY1SLDWl6dqrZa9k5_4nA',
    appId: '1:807190543184:ios:53a54597a38b03ca54ca55',
    messagingSenderId: '807190543184',
    projectId: 'pet-pal-e8664',
    storageBucket: 'pet-pal-e8664.appspot.com',
    iosBundleId: 'com.example.petpal.RunnerTests',
  );
}
